version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mysql-network
    restart: always
  
  auth_service:
    build:
      context: ./microservice_project/auth/
      dockerfile: Dockerfile  # Path to your Flask application's Dockerfile
    container_name: auth_service
    environment:
      MYSQL_HOST: mysql  # Connect to the MySQL container (docker service name)
      MYSQL_USER: my_user
      MYSQL_PASSWORD: user_password
      MYSQL_DB: my_database
      JWT_SECRET: leogalerugholrgnjlaebn
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - mysql-network
    restart: always


volumes:
  mysql-data:

networks:
  mysql-network:
    driver: bridge
